name       : lugaru
version    : 1.2
release    : 2
source     :
    - git|https://gitlab.com/osslugaru/lugaru : 1.2 
license    :
    - CC-BY-SA-3.0
    - CC-BY-SA-4.0
    - GPL-2.0
component  : games.action
summary    : Lugaru (pronounced Loo-GAH-roo) is a cross-platform third-person action game
description: |
    Lugaru (pronounced Loo-GAH-roo) is a cross-platform third-person action game
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libpng)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(vorbis)
    - libjpeg-turbo-devel
setup      : |
    %cmake -DSYSTEM_INSTALL=ON .
build      : |
    %make
install    : |
    %make_install
